version: '3'

services:
  # 阶段1：临时Web服务（仅用于证书申请）
  temp-web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - web-root:/var/www/html
      - ./nginx-init.conf:/etc/nginx/nginx.conf
      - nginx-cache:/var/cache/nginx
    networks:
      - app-network
    user: "root"
    entrypoint: sh -c "mkdir -p /var/cache/nginx && chown -R nginx:nginx /var/cache/nginx && nginx -g 'daemon off;'"
    restart: unless-stopped

  # 阶段2：证书申请服务
  certbot:
    image: certbot/certbot
    depends_on:
      - temp-web
    volumes:
      - certbot-etc:/etc/letsencrypt
      - web-root:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email 362732414@qq.com --non-interactive --agree-tos --no-eff-email -d ca.chanchun.net --staging
    networks:
      - app-network
    restart: unless-stopped

  # 阶段3：正式Web服务
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - web-root:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    restart: unless-stopped

volumes:
  web-root:
  certbot-etc:
  certbot-var:
  nginx-cache:

networks:
  app-network:
