# docker-compose.yml
version: '3'

services:
  # 阶段1：证书申请专用服务（临时占用80端口）
  certbot-setup:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - certbot-www:/usr/share/nginx/html
      - certbot-etc:/etc/letsencrypt
    command: >
      sh -c "echo 'Starting temporary certbot setup...';
             mkdir -p /usr/share/nginx/html/.well-known/acme-challenge;
             nginx -g 'daemon off;' & 
             sleep 5;
             certbot certonly --webroot -w /usr/share/nginx/html -d ca.chanchun.net 
               --email 362732414@qq.com --agree-tos --no-eff-email --staging;
             kill %1;
             echo 'Certbot setup completed'"
    networks:
      - app-network

  # 阶段2：正式Web服务（使用证书）
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - certbot-setup
    restart: unless-stopped

volumes:
  certbot-etc:
  certbot-www:

networks:
  app-network: